# Generated by Django 2.2 on 2020-08-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя Фамилия')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50, verbose_name='Имя Фамилия')),
                ('phone_user', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserFirst')),
            ],
            options={
                'verbose_name': 'Контакты по id',
            },
        ),
    ]
